import type { Metadata } from 'next'
import '../globals.css'
import { Header, Footer } from '@/components/layout/common'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='flex flex-col min-h-svh container mx-auto'>
        <Header />
        <main className='flex flex-1'>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
