import type { Metadata } from 'next'
import '../globals.css'

export const metadata: Metadata = {
  title: 'Create Next Apasdfp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        대시보드(utm) 레이아웃(사이드바)
        {children}
      </body>
    </html>
  )
}
